server:
  port: 8761
spring:
  application:
    name: eureka-provider
#Eureka 相关配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    # 是否从其他的服务中心同步服务列表 => 当只一个eureka 节点的时候，这里为 false，多个节点互相注册的时候就为true
    fetch-registry: false
    # 是否把自己作为服务注册到其他服务注册中心
    register-with-eureka: false
